[project]
name = "pika"
org = "org.pikachat"

[core]
crate = "pika_core"
bindings = "uniffi"

[ios]
bundle_id = "org.pikachat.pika"
scheme = "Pika"

[android]
app_id = "org.pikachat.pika"
avd_name = "pika_api35"
