name: pre-merge

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Nix store cache
      - uses: actions/cache@v4
        with:
          key: nix-v1-${{ runner.os }}-${{ hashFiles('flake.lock') }}
          restore-keys: nix-v1-${{ runner.os }}-
          path: /nix
      - uses: nixbuild/nix-quick-install-action@v30

      # Cargo cache
      - uses: actions/cache@v4
        with:
          key: cargo-v1-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: cargo-v1-${{ runner.os }}-
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target

      - name: Format
        run: nix develop -c just fmt

      - name: Clippy
        run: nix develop -c cargo clippy -p pika_core --lib --tests -- -D warnings

      - name: Test
        run: nix develop -c cargo test -p pika_core --lib --tests

      - name: Build CLI
        run: nix develop -c cargo build -p pika-cli
